[package]
name = "mscript"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
pest = "2.5.6"
pest_consume = "1.1.3"
pest_derive = "2.5.6"
pratt = "0.4.0"
