[package]
name = "bytecode"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
lazy_static = "1.4.0"
libloading = "0.8.0"
once_cell = "1.17.1"

[features]
string_instructions = []
developer = []
