[package]
name = "bytecode_dev_transpiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytecode = { path = "../bytecode" }
anyhow = "1.0.69"

